### ISSUE TITLE
nixos/nix not working anymore ?

### ISSUE THREAD

**Issue by juliendehos** [NixOS/docker#1]
Hi, I use the nixos/nix docker image in a gitlab-ci pipeline but the latest image does not work anymore.

- build status:
```
$ nix-build
/bin/sh: eval: line 59: nix-build: not found
ERROR: Job failed: exit code 127
```
https://gitlab.com/juliendehos/cppythonix/-/jobs/76635260

- .gitlab-ci.yml (working perfectly 2 days ago):
```
image: nixos/nix
build:
    script:
        - nix-build
    only:
        - master
```

Any idea ?
